# app/services/food_query_planner.py
#
# FoodQueryPlanner — single nano LLM call that generates coherent search queries
# for all food pipeline tools (MCP recipe database and Tavily web search).
#
# Separated from recipe_fetcher.py because query planning is a cross-cutting
# concern: Mode 3 (food_info) needs a Tavily query but never calls MCP.
# Mode 1 (food_recipes) needs only an MCP query. Mode 2 needs both.
#
# Key design decision:
#   Both queries — when needed — are generated by the SAME nano LLM call from the
#   SAME pet context and the SAME interpretation of the user's intent. This guarantees
#   coherence: MCP and Tavily are searching aligned aspects of the same question,
#   not two independent interpretations.
#
# Usage by mode:
#   food_recipes      → plan.mcp_query only    (Tavily not called)
#   food_recipes_info → plan.mcp_query + plan.tavily_query  (both tools run in parallel)
#   food_info         → plan.tavily_query only  (MCP not called)

import json
import logging
import time
from dataclasses import dataclass

from app.llm.base import LLMProvider, LLMProviderError

logger = logging.getLogger(__name__)

# MCP recipe database vocabulary.
# These are the terms the embedding model was trained on.
# The nano LLM must prefer these when building the mcp_query.
_MCP_VOCABULARY = (
    "関節ケア, 皮膚ケア, 毛並みケア, 低脂質, 高たんぱく, ダイエット, 水分補給, "
    "シニアケア, 消化しやすい, 体重管理, 低カロリー, 食欲不振, 筋肉維持, 腎臓ケア"
)


@dataclass
class QueryPlan:
    """
    Output of plan_food_queries().

    Fields present depend on the mode:
      food_recipes:      mcp_query set, tavily_query is empty string
      food_recipes_info: both set
      food_info:         tavily_query set, mcp_query is empty string

    Always check the field before using it — do not assume both are populated.
    """
    mcp_query: str = ""      # Japanese semantic query for recipe database
    tavily_query: str = ""   # Web search query for veterinary/nutrition content


async def plan_food_queries(
    llm: LLMProvider,
    mode: str,
    user_message: str,
    pet_profile: dict,
    active_profile: dict,
    conversation_history: list[dict] | None = None,
    language: str = "JA",
) -> QueryPlan:
    """
    Build search queries for the food pipeline using a single nano LLM call.

    Generates only what the mode needs — no wasted tokens:
      food_recipes:      mcp_query only
      food_recipes_info: both queries
      food_info:         tavily_query only

    Falls back gracefully on LLM failure:
      mcp_query fallback  → raw user_message (same as old build_recipe_query behaviour)
      tavily_query fallback → user_message + species + conditions (rule-based safety net)

    Args:
        llm:                  LLMProvider instance (nano model used internally).
        mode:                 "food_recipes" | "food_recipes_info" | "food_info"
        user_message:         Current user chat message.
        pet_profile:          Static pet identity dict (species, breed, life_stage).
        active_profile:       Dynamic facts dict; each entry has a 'value' key.
        conversation_history: Last N chat turns for context carryover (optional).
        language:             "JA" or "EN" — determines tavily_query language.

    Returns:
        QueryPlan with the relevant fields populated.
    """
    need_mcp = mode in ("food_recipes", "food_recipes_info")
    need_tavily = mode in ("food_recipes_info", "food_info")

    # ── Build pet profile context ──────────────────────────────────────────────

    def ap_val(key: str) -> str:
        entry = active_profile.get(key, {})
        if isinstance(entry, dict):
            return str(entry.get("value", "")).strip()
        return str(entry).strip()

    life_stage = pet_profile.get("life_stage") or ap_val("life_stage") or "adult"
    species = pet_profile.get("species") or "dog"
    conditions = ap_val("chronic_illness")
    symptoms = ap_val("symptoms")

    profile_lines = [
        f"Species: {species}",
        f"Life stage: {life_stage}",
    ]
    if pet_profile.get("breed"):
        profile_lines.append(f"Breed: {pet_profile['breed']}")
    if conditions:
        profile_lines.append(f"Known conditions: {conditions}")
    if symptoms:
        profile_lines.append(f"Active symptoms: {symptoms}")
    if ap_val("appetite"):
        profile_lines.append(f"Appetite: {ap_val('appetite')}")
    if ap_val("water_intake"):
        profile_lines.append(f"Water intake: {ap_val('water_intake')}")
    if ap_val("stool_condition"):
        profile_lines.append(f"Stool condition: {ap_val('stool_condition')}")
    bcs = ap_val("body_condition_score")
    if bcs:
        profile_lines.append(f"Body condition score: {bcs}/9 (5=ideal, >6=overweight)")
    if ap_val("weight_trend"):
        profile_lines.append(f"Weight trend: {ap_val('weight_trend')}")
    activity = ap_val("activity_level")
    if activity:
        profile_lines.append(f"Activity level: {activity.split()[0]}/5")

    # ── Recent conversation context ────────────────────────────────────────────

    recent_context = ""
    if conversation_history:
        last_six = conversation_history[-6:]
        turns = "\n".join(
            f"{'User' if t['role'] == 'user' else 'Assistant'}: {t['content'][:120]}"
            for t in last_six
        )
        recent_context = f"\n\nRecent conversation:\n{turns}"

    # ── Build system prompt — only include field specs for what this mode needs ─

    field_specs: list[str] = []

    if need_mcp:
        field_specs.append(f"""\
"mcp_query": <string>
  Japanese semantic search for a pet recipe database, 40-100 characters.
  - Natural Japanese only — no English words.
  - Do NOT include allergen ingredient names (they are filtered separately).
  - Prefer this vocabulary: {_MCP_VOCABULARY}
  - Priority order: user's explicit food request → active health symptoms → life stage/breed.""")

    if need_tavily:
        tavily_lang_instruction = (
            "Japanese (日本語) — target Japanese veterinary and nutrition websites."
            if language == "JA"
            else "English — target authoritative veterinary and nutrition websites."
        )
        tavily_example = (
            '"シニア犬 腎臓病 低脂質食 栄養管理 食事療法"'
            if language == "JA"
            else '"low-fat diet senior dog chronic kidney disease nutrition veterinary"'
        )
        field_specs.append(f"""\
"tavily_query": <string>
  Web search query for clinical veterinary/nutrition content, 10-20 words.
  - Language: {tavily_lang_instruction}
  - Include: species, specific health conditions, nutrition angle.
  - Aim for clinical, evidence-based results a vet would cite.
  - Example: {tavily_example}""")

    # Build the JSON shape description for the prompt
    json_shape_parts = []
    if need_mcp:
        json_shape_parts.append('"mcp_query": "..."')
    if need_tavily:
        json_shape_parts.append('"tavily_query": "..."')
    json_shape = "{\n  " + ",\n  ".join(json_shape_parts) + "\n}"

    system_prompt = f"""\
You build search queries for a pet food AI assistant.
Return ONLY a JSON object with exactly {"these two keys" if need_mcp and need_tavily else "this key"} — no explanation, no markdown, no extra keys.

{json_shape}

Field rules:
{chr(10).join(field_specs)}"""

    user_prompt = (
        f"Pet profile:\n{chr(10).join(profile_lines)}"
        f"{recent_context}"
        f"\n\nUser's current message: {user_message}"
    )

    # ── Call nano LLM ──────────────────────────────────────────────────────────

    t0 = time.perf_counter()
    try:
        raw = await llm.complete(
            system_prompt=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
            temperature=0.0,
            max_tokens=200,
            model="gpt-5.4-nano",
        )
        elapsed = time.perf_counter() - t0

        # Strip markdown fences if model added them
        text = raw.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        data = json.loads(text)
        plan = QueryPlan(
            mcp_query=str(data.get("mcp_query", "")).strip(),
            tavily_query=str(data.get("tavily_query", "")).strip(),
        )

        logger.info(
            "FoodQueryPlanner: %.2fs | mode=%s | mcp_query=%r | tavily_query=%r",
            elapsed, mode, plan.mcp_query, plan.tavily_query,
        )
        return plan

    except (LLMProviderError, json.JSONDecodeError, KeyError, TypeError) as exc:
        elapsed = time.perf_counter() - t0
        logger.warning(
            "FoodQueryPlanner: failed in %.2fs (%s) — falling back to safe defaults",
            elapsed, exc,
        )
        return _fallback_plan(
            need_mcp=need_mcp,
            need_tavily=need_tavily,
            user_message=user_message,
            species=species,
            life_stage=life_stage,
            conditions=conditions,
            language=language,
        )


def _fallback_plan(
    need_mcp: bool,
    need_tavily: bool,
    user_message: str,
    species: str,
    life_stage: str,
    conditions: str,
    language: str,
) -> QueryPlan:
    """
    Rule-based fallback when the nano LLM call fails.

    mcp_query fallback:    raw user_message (MCP is tolerant — will find something)
    tavily_query fallback: basic pet context appended to user message
    """
    mcp_query = user_message if need_mcp else ""

    tavily_query = ""
    if need_tavily:
        if language == "JA":
            species_term = "犬" if species == "dog" else "猫"
            stage_term = "シニア" if life_stage == "senior" else ""
            parts = [user_message, species_term, stage_term, conditions, "栄養 食事"]
            tavily_query = " ".join(p for p in parts if p)
        else:
            parts = [user_message, species, life_stage if life_stage != "adult" else "",
                     conditions, "nutrition veterinary"]
            tavily_query = " ".join(p for p in parts if p)

    logger.info(
        "FoodQueryPlanner fallback — mcp_query=%r tavily_query=%r",
        mcp_query, tavily_query,
    )
    return QueryPlan(mcp_query=mcp_query, tavily_query=tavily_query)
