"""add composite indexes for history builder and nightly queries

Revision ID: 1d20aafa64c5
Revises: 707a460b11df
Create Date: 2026-03-19 16:33:54.646413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d20aafa64c5'
down_revision: Union[str, Sequence[str], None] = '707a460b11df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fact_log_pet_id_extracted_at', 'fact_log', ['pet_id', 'extracted_at'], unique=False)
    op.create_index('ix_threads_expires_at', 'threads', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_expires_at', table_name='threads')
    op.drop_index('ix_fact_log_pet_id_extracted_at', table_name='fact_log')
    # ### end Alembic commands ###
