"""add fact_log indexes and widen field_key to 128

Revision ID: 1e14c749ed04
Revises: d6c1e9df2f80
Create Date: 2026-03-13 18:06:22.541379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e14c749ed04'
down_revision: Union[str, Sequence[str], None] = 'd6c1e9df2f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_profile', 'field_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('fact_log', 'field_key',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_index('ix_fact_log_pet_id', 'fact_log', ['pet_id'], unique=False)
    op.create_index('ix_fact_log_session_id', 'fact_log', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_log_session_id', table_name='fact_log')
    op.drop_index('ix_fact_log_pet_id', table_name='fact_log')
    op.alter_column('fact_log', 'field_key',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('active_profile', 'field_key',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
