"""add_user_code_to_active_profile_fact_log_pets

Revision ID: 37a225edf357
Revises: 1d20aafa64c5
Create Date: 2026-03-20 12:31:29.460493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a225edf357'
down_revision: Union[str, Sequence[str], None] = '1d20aafa64c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="" fills existing rows with empty string (avoids NOT NULL violation).
    op.add_column('active_profile', sa.Column('user_code', sa.String(length=64), nullable=False, server_default=''))
    op.create_index('ix_active_profile_user_code', 'active_profile', ['user_code'], unique=False)
    op.add_column('fact_log', sa.Column('user_code', sa.String(length=64), nullable=False, server_default=''))
    op.create_index('ix_fact_log_user_code', 'fact_log', ['user_code'], unique=False)
    op.add_column('pets', sa.Column('user_code', sa.String(length=64), nullable=False, server_default=''))
    op.create_index('ix_pets_user_code', 'pets', ['user_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pets_user_code', table_name='pets')
    op.drop_column('pets', 'user_code')
    op.drop_index('ix_fact_log_user_code', table_name='fact_log')
    op.drop_column('fact_log', 'user_code')
    op.drop_index('ix_active_profile_user_code', table_name='active_profile')
    op.drop_column('active_profile', 'user_code')
    # ### end Alembic commands ###
