"""add_secondary_pet_id_to_threads

Revision ID: 3d45928e6e16
Revises: d7e0f4a8b9c3
Create Date: 2026-03-17 12:18:10.806882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d45928e6e16'
down_revision: Union[str, Sequence[str], None] = 'd7e0f4a8b9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('secondary_pet_id', sa.Integer(), nullable=True))
    op.create_index('ix_threads_secondary_pet_id', 'threads', ['secondary_pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_secondary_pet_id', table_name='threads')
    op.drop_column('threads', 'secondary_pet_id')
    # ### end Alembic commands ###
