"""redesign_users_table_w18

Revision ID: 62b04c546a07
Revises: 3d45928e6e16
Create Date: 2026-03-17 12:21:38.068687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b04c546a07'
down_revision: Union[str, Sequence[str], None] = '3d45928e6e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_code', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('users', sa.Column('display_name', sa.String(length=128), nullable=False, server_default=''))
    op.add_column('users', sa.Column('conversation_style', sa.String(length=32), nullable=False, server_default='new'))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=4), nullable=False, server_default='auto'))
    op.add_column('users', sa.Column('created_at', sa.String(length=64), nullable=False, server_default=''))
    op.drop_constraint(op.f('users_user_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_code'])
    op.drop_column('users', 'pet_id')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_user_id_key'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'conversation_style')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'user_code')
    # ### end Alembic commands ###
