"""drop pets table (AALDA is sole source of truth)

Revision ID: ca002cd94239
Revises: 37a225edf357
Create Date: 2026-03-20 13:03:53.914385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca002cd94239'
down_revision: Union[str, Sequence[str], None] = '37a225edf357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_user_code'), table_name='pets')
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('species', sa.VARCHAR(length=32), server_default=sa.text("'dog'::character varying"), autoincrement=False, nullable=False),
    sa.Column('breed', sa.VARCHAR(length=128), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(length=16), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(length=16), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('life_stage', sa.VARCHAR(length=16), server_default=sa.text("'adult'::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pets_pkey')),
    sa.UniqueConstraint('pet_id', name=op.f('pets_pet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pets_user_code'), 'pets', ['user_code'], unique=False)
    # ### end Alembic commands ###
