"""add pet_label to fact_log

Revision ID: d65ce8144b53
Revises: e6df30dc881f
Create Date: 2026-03-17 16:20:12.060349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65ce8144b53'
down_revision: Union[str, Sequence[str], None] = 'e6df30dc881f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_log', sa.Column('pet_label', sa.String(length=8), nullable=False, server_default='pet_a'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_log', 'pet_label')
    # ### end Alembic commands ###
