"""create initial tables

Revision ID: d6c1e9df2f80
Revises: 
Create Date: 2026-03-13 17:20:08.594437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c1e9df2f80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.String(length=64), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_rank', sa.String(length=32), nullable=True),
    sa.Column('time_scope', sa.String(length=16), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('change_detected', sa.Text(), nullable=True),
    sa.Column('trend_flag', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id', 'field_key', name='uq_active_profile_pet_field')
    )
    op.create_table('fact_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_rank', sa.String(length=32), nullable=False),
    sa.Column('time_scope', sa.String(length=16), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('needs_clarification', sa.Boolean(), nullable=False),
    sa.Column('extracted_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('species', sa.String(length=32), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.String(length=16), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.Column('life_stage', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('pet_id', sa.String(length=64), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('relationship_summary', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pets')
    op.drop_table('fact_log')
    op.drop_table('active_profile')
    # ### end Alembic commands ###
