"""drop conversation_style from users

Revision ID: e6df30dc881f
Revises: 62b04c546a07
Create Date: 2026-03-17 16:08:03.212274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6df30dc881f'
down_revision: Union[str, Sequence[str], None] = '62b04c546a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'conversation_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('conversation_style', sa.VARCHAR(length=32), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
